TrajectoryPlannerROS:

  max_vel_x: 0.3
  min_vel_x: 0.04
  max_vel_theta: 0.4
  min_in_place_vel_theta: 0.05

  acc_lim_x: 0.1
  acc_lim_theta: 0.1

  holonomic_robot: false
  escape_vel: -0.1

  meter_scoring: true
